version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/findog
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: deploy.sh
      runas: ubuntu
